---
version: 2
registries:
    savilleNuget:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/savilleassessment/UK/_packaging/OasysCore/nuget/v3/index.json
    username: geoffrey.rogers@savilleassessment.com
    password: ${{secrets.MY_AZURE_DEVOPS_TOKEN}}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries: "savilleNuget"
    schedule:
      interval: "daily"
      time: "16:55"
    open-pull-requests-limit: 1
